### ISSUE TITLE
Improve security of login and signup (reduce info + add salt)

### ISSUE THREAD

**Issue by jgao222** [winstonbullen/DuoCode#24]
https://github.com/winstonbullen/DuoCode/blob/decb1d8966cd35f2bd2408dbf64cd768cbcacb39/backend/src/index.ts#L76-L79

https://github.com/winstonbullen/DuoCode/blob/decb1d8966cd35f2bd2408dbf64cd768cbcacb39/backend/src/index.ts#L83-L86

In addition to addressing the above TODO, it would also be good to add salt to the hashed stored passwords.

**Comment by winstonbullen** [comment]
1. The information about why a login fails was discussed and it was decided to keep the current information. This might change, but is not worthy of an issue on its own. This would likely be part of a final style pass before final release.
2. Bcrypt manages salting automatically. The team figured this out recently and thus this issue was not assigned to a pull request Going to close this issue since it has been addressed implicitly.
