### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by asagrekin** [winstonbullen/DuoCode#65]
**Describe the bug**
Can't click on the 4th option during button selection portion of the quizzes.

**To Reproduce**
1. Go to the home page.
2. Click on one of the quizzes (the first very first one will work, so unit 1 and the first star).
3. Continue through the quiz until a question that involves clicking on one of 4 buttons to answer it.
4. Hover over the 4th option (the one at the bottom).
5. When trying to click, the button will not change to selected state.

**Expected behavior**
Should allow the user to click it, so that it is selected as the answer to the question.

**Screenshots**
https://github.com/winstonbullen/DuoCode/assets/75052058/075ef95a-715b-45b8-94ba-0070410ede1b

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Was able to reproduce on both chrome and safari.
 - Version: Latest

**Comment by winstonbullen** [comment]
Thank you for the feedback. This is actually an issue with UI scaling as mentioned in the [user documentation](https://duocode.onrender.com/). Note that if you are logged in, the landing page containing user documentation redirects to the home page. Changing resolution to 1920x1080 and ensuring app scaling is off fixes this. Scaling is on the agenda for front end.

**Comment by winstonbullen** [comment]
Keeping this bug report to track front end's scaling TODO.

**Comment by asagrekin** [comment]
I can't find any user documentation. That link takes me to the home page of
the site, but I don't see any links to documentation there.

**Comment by winstonbullen** [comment]
The user documentation is the landing page of the site. Again, this will not be visible if you are logged in. We plan on fixing this so the user documentation is viewable even for logged-in users. Opening the link in an incognito tab will solve this. The user documentation is brief because the website requires little instruction (no setup, build instructions, etc.). Here is a screenshot of what the page should look like.
![image](https://github.com/winstonbullen/DuoCode/assets/52332581/f8171791-c79d-4a8d-99d8-6d8deb7c4d30)
